name: tempo
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  font_awesome_flutter: ^10.1.0
  shared_preferences: ^2.0.6
  provider: ^6.0.0
  get: ^4.6.1
  flex_color_scheme: ^5.0.1
  connectivity_plus: ^2.0.2
  qr_flutter: ^4.0.0
  dio: ^4.0.0
  shimmer: ^2.0.0
  date_time_picker: ^2.1.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  permission_handler: ^9.1.0
  cached_network_image: ^3.2.0
  numberpicker: ^2.1.1
  firebase_messaging: ^11.2.11
  firebase_analytics: ^9.1.2
  firebase_core: ^1.12.0
  flutter_local_notifications: ^9.5.2
  carousel_slider: ^4.0.0
  fluttertoast: ^8.0.8
  sms_otp_auto_verify: ^2.1.0
  webview_flutter: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: "^0.9.2"
flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icons/logo.png"
  adaptive_icon_foreground: "assets/icons/logo.png"
  adaptive_icon_background: "#ff0000"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/payments/
    - assets/images/icons/
    - assets/images/
    - assets/json/
    - assets/fonts/

  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300