import 'package:get/get.dart';

class LocaleString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        //ENGLISH LANGUAGE
        'en': {
          'all': 'All',
          'about_us': 'About us',
          'contact_us': 'Contact us',
          'about_developer': 'About developer',
          'privacy_policy': 'Privacy policy',
          'home': 'Home',
          'premium': 'Premium',
          'receipt': 'Receipt',
          'more': 'More',
          'recommended': 'Recommended',
          'book_now': 'Book now',
          'select_room': 'Select room',
          'premium_user': 'Premium User',
          'sign_in': 'Sign',
          'sign_up': 'Sign up',
          'no_category': 'No categories found',
          'region': 'Region',
          'categories': 'Categories',
          'no_thumbnails': 'No thumbnails',
          'settings': 'Settings',
          'online_tempo_tempo': 'Temporary tempo',
          'smart_tempo': 'Smart tempo With Privacy',
          'premium_description':
              'You do not have premium account, with premium account you will you will be abel to view more, services, and many more staning features. If you have an an account click sign in otherwise click signup button to register as a premium user. ',
          'language_description':
              'You can change the application language without changing the whole phone locale, you can click the option button bellow to change the languate to your prefered option, you can also change the language a the home page near the notification button button',
          'settings_description':
              'Change your screen view mode, you can change to light mode or dark mode. The default settings is dark mode. You click the button of your option bellow',
          'english': 'English',
          'swahili': 'Swahili',
          'light_mode': 'Light Mode',
          'dark_mode': 'Dark Mode',
          'All': 'All',
          'Hotels': 'Hotels',
          'Rentals': 'Rentals',
          'Lodges': 'Lodges',
          'Venues': 'Venues',
          'Offices': 'Offices',
          'Houses': 'Houses',
          'save': 'Save',
          'cancel': 'Cancel',
          'sign_in_premium_account': 'Sign in premium account',
          'premium_account': 'Premium Account',
          'phone_number': 'Phone number',
          'password': 'Password',
          'not_member_yet': 'Not member yet?',
          'create_account': 'Create Account',
          'have_an_account': 'Have an account?',
          'invalid_phone': 'Invalid phone number',
          'too_short': 'Too short password',
          'invalid_credentials': 'Invalid credentials',
          'account_created_successfully': 'Account created successfully',
          'password_': 'Enter correct password!',
          'phone_': 'Enter correct phone !',
          'terms_conditions':
              'esponsive HTML tempthat is based on the CSS framework Bootstrap 4 and it is built with Sass. Sass compiler makes it easier to code and customize. If you are unfamiliar with Bootstrap or Sass, visit their website and read through the documentation. All of Bootstrap components have been modified to fit the style of Plus Admin and provide a consistent look throughout the tempBefore you start working with the template, we suggest you go through the pages that are bundled with the theme. Most of the tempexample pages contain quick tips on how to create or use a component which can be really helpful when you need to create something on the fly Note: We are trying our best to document how to use the template. If you think that something is missing from the documentation, please do not hesitate to tell us about it. If you have any questions or issues regarding this theme please use Envato support form on our profile or email us at support@bootstrapdash.com Getting started You can directly use the compiled and ready-to-use the version of the template. But in case you plan to customize the tempextensively the tempallows you to do so. Within the download you\'ll find the following directories and files, logically grouping common assets and providing both compiled and minified variations Note: The root folder denoted further in this documentation refers to the \'template\' folder inside the downloaded folder We have bundled up the vendor files needed for demo purpose into a folder  you may not need all those vendors in your application. If you want to make any change in the vendor package files, you need to change the src path for related tasks in the file gulpfile.js and run the task bundleVendors to rebuild the vendor files. Installation You need to install package files/Dependencies for this project if you want to customize it. To do this, you must have node and npm installed in your computer. Installation guide of the node can be found here. As npm comes bundled with a node, a separate installation of npm is not needed. If you have installed them, just go to the root folder and run the following command in your command prompt or terminal (for the mac users). npm install This will install the dev dependencies in the local node_modules folder in your root directory.Then you will need to install Gulp. We use the Gulp task manager for the development processes. Gulp will watch for changes to the SCSS files and automatically compile the files to CSS. Getting started with Gulp is pretty simple. The Gulp site is a great place to get information on installing Gulp if you need more information. You need to first install Gulp-cli in your machine using the below command. npm install -g gulp-cli This installs Gulp-cli globally to your machine. The other thing that Gulp requires, which, is really what does all the work, is the gulpfile.js. In this file, you set up all of your tasks that you will run. Don\'t worry. We have this file already created for you To run this project in development mode enter the following command below. This will start the file watch by gulp and whenever a file is modified, the SCSS files will ',
          'terms_conditions_title': 'Terms and conditions',
          'finish': 'Finish',
          'check_in': 'Check In',
          'check_out': 'Check Out',
          'date': 'Date',
          'hour': 'Hour',
          'booking_summary': 'Booking Summary',
          'entry_date': 'Entry',
          'exit_date': 'Exit',
          'total_hours': 'Staying Hours',
          'price': 'Price per hour',
          'total': 'Total',
          'pay_now': 'Pay now',
          'choose_room': 'Choose room',
          'payment_reference_number': 'REFERENCE NUMBER',
          'mpesa_guide':
              '1. Tap the icon to copy reference number,\n2. Dial *150*00# OK,\n3. Choose # 3, Pay by Mpesa,\n4. Select # 2 enter business number,\n5. Enter the business number 3364545,\n6. Enter the copied reference number,\n7. Enter your M-PESA PIN and confirm,\n8. Return to the App and wait for a while.',
          'are_you_sure_you_want_to_cancel':
              'Are you sure you want to cancel payment?\nCanceling payment will disable automatic update, cancel only if you have postponed payment.',
          'waiting_for_payment': 'Waiting for payment',
          'waiting': 'Waiting...',
          'yes': 'Yes',
          'no': 'No',
          'no_reference_number': 'NO REFERENCE NUMBER',
          'payment_made_successfully':
              'Your payment was successfully received to our end, your booking is reserved',
          'invalid_reference_number':
              'Your payment reference number was not generated as expected due to failure to meet some conditions. Kindly  read the message display to you, fix it and and try again. If the problem continues do not hesitate to call us via our contacts in the more page.',
          'choose_operator': 'Choose operator',
          'continue': 'Continue',
          'continue_with_payment': 'Continue with payments',
          'your_purchase_was_successfully': 'Your purchase was successfull',
          'your_payment_receipt_details': 'Your payment recept details',
          'nb': 'ALERT',
          'do_not_share':
              'The payment receipt is a confidential code do not share with anyone.',
          'no_house_found': 'No house in this category',
          'no_house_found_description':
              'There is no item found for this category, this happens when the selected category does not match to data from our databases. Please check this category after a while to see the data is uploaded.',
          'book_house': 'Book House',
          'other': 'Other',
          'you_have_no_receipt': 'No active receipt found',
          'no_receipt_description':
              'You do not have an active receipt currently, the active pending receipt will be displayed here.',
          'no_service_found_for': 'No services found for',
          'no_service_found_description':
              'You have no services found in this description, there is no matching data from our databases, this happen when services under this category aren\'t or have been removed by the owner.',
          'category_two': 'category',
          'price_per_hour': 'Price per hour',
          'price_per_day': 'Price per day',
          'total_days': 'Total days',
          'days': 'Days',
          'hours': 'Hours',
          'minimum_days': 'The minimum booking is ',
          'minimum_hours': 'The minimum booking is ',
          'days_jm': ' days',
          'hours_jm': ' hours',
          'choose_duration': 'Please select duration interval',
          'amount': 'Amount',
          'try_fix': 'Fix the issue',
          'seach_by_name_region_district': 'Search by name region or district',
          'search_regions': 'Search regions',
          'ok': 'OK',
          'no_results_found_for': 'No results found for ',
          'no_service_found_description_search':
              'No results found for you search, please check your search keyword and try again.',
          'booking_type': 'Choose booking type',
          'personal_booking': 'Personal booking',
          'cooperate_booking': 'Cooperate booking',
          'book': 'Book',
          'cooperate_number': 'Cooperate number',
          'number_of_rooms': 'Number of rooms',
          'booked_rooms': 'Rooms',
          'enter_cooperate_number': 'Cooperate number is required',
          'cooperate_number_short': 'Cooperate',
          'check_guide':
              'You have successfully reserved the room for cooperate, keep the above reference for later attachment. Please keep the terms and conditions that applies for cooperate booking.',
          'reference_number': 'Reference',
          'confirm_operation': 'Precaution',
          'no_description':
              'No description provided by the manager of this service, in case something is missing you may call to ask at any time',
          'created_account': 'Create an account',
          'create_premium_account': 'Create an Account',
          'change_password_desc':
              'When your password is successfully updated you will be logged out. From there you will be required to use your new password to sign in.',
          'we_have_sent_code': 'We have send an SMS with a code to\nnumber ',
          'enter_otp_here': 'Enter OTP code here',
          'fill_all': 'Please fill all fields to create account!',
          'password_mismatches': 'Passwords mismatches',
          'category': 'Category',
          'street': 'Street',
          'transport': 'Transport',
          'public_transport': 'Public transport',
          'private_transport': 'Private transport',
          'view_map': 'View on google map',
          'country': 'Country',
          'electricity': 'Electricity',
          'rented_as_house': 'Rented as house',
          'rented_as_rooms': 'Rented as room',
          'months': ' Months',
          'water': 'Water',
          'view_details': 'View details',
          'view_rooms': 'View rooms',
          'price_per_month': 'Price per month',
          'available': 'Available',
          'house_details': 'House details',
          'name': 'Name',
          'contact_phone': 'Contact Phone',
          'copied': 'Content copied successfully',
          'min_booking_months': 'Min booking months',
          'identity': 'Identity',
          'payments': 'PAYMENTS',
          'no_data': 'No data available',
          'no_map': 'No map available',
          'use_reference_to_pay':
              'You are required to pay so as you can view the details of this service. Beware that after paying the count starts and will last only for three hours.',
          'payment_received': 'You paid successfully',
          'see_more': 'View more..',
          'view_more': 'View more..',
          'login_to_verify':
              'You are not currently logged in, please login or create account so that we can verify if you have paid for this service or not.',
          'are_you_sure': 'Are you sure you want to logout?',
          'selcom_portal': 'SELCOM PORTAL',
          'data_hidden': 'Details is hidden, pay to view',
          'map_hidden': 'Map is hidden pay to view',
          'payment_methods': 'Payment Methods',
          'payment_expired': 'This payment is expired', 
          'repay': 'Pay Again',
        },

        //SWAHILI LANGUAGE
        'sw': {
          'all': 'Zote',
          'about_us': 'Kuhusu sisi',
          'contact_us': 'Wasiliana nasi',
          'about_developer': 'Kuhusu developa',
          'privacy_policy': 'Sera za faragha',
          'home': 'Nyumbani',
          'premium': 'Primiamu',
          'receipt': 'Risiti',
          'more': 'Zaidi',
          'recommended': 'Zilizopendekezwa',
          'book_now': 'Lipia sasa',
          'select_room': 'Chagua chumba',
          'premium_user': 'Mtumiaji wa primiamu',
          'sign_in': 'Ingia',
          'sign_up': 'Unda akaunti',
          'no_category': 'Hakuna kitengo kilichopatikana',
          'region': 'Mkoa',
          'categories': 'Vitengo',
          'no_thumbnails': 'Hakuna picha',
          'settings': 'Mipangilio',
          'online_tempo_tempo': 'Lipia kwa muda',
          'smart_tempo': 'Lipia smati kwa faragha',
          'language_description':
              'Unaweza kubadilisha lugha bila kubadilisha eneo lote la simu, unaweza kubofya kitufe cha chaguo kugeuza kubadili kuteleza kwa chaguo lako unalopendelea, unaweza pia kubadilisha lugha ya ukurasa wa nyumbani karibu na kitufe cha kitufe cha taarifa.',
          'premium_description':
              'Huna akaunti ya malipo, ukiwa na akaunti ya malipo ya kwanza utakuwa na uwezo wa kuona zaidi, huduma, na huduma zingine nyingi za kudharau. Ikiwa una akaunti bonyeza ishara ingia vinginevyo bonyeza kitufe cha kujisajili ili ujiandikishe kama mtumiaji wa malipo. ',
          'settings_description':
              'Badilisha hali yako ya kutazama skrini, unaweza kubadilisha kuwa hali nyepesi au hali nyeusi. Mipangilio chaguomsingi ni hali ya giza. Unabofya kitufe cha chaguo lako',
          'english': 'Kiingereza',
          'swahili': 'Kiswahili',
          'light_mode': 'Modi Angavu',
          'dark_mode': 'Modi Kiza',
          'All': 'Zote',
          'Hotels': 'Hoteli',
          'Lodges': 'Loji',
          'Venues': 'Kumbi',
          'Offices': 'Ofisi',
          'Houses': 'Nyumba',
          'save': 'Tunza',
          'cancel': 'Ghairi',
          'check_in': 'Kuingia',
          'check_out': 'Kutoka',
          'date': 'Tarehe',
          'hour': 'Saa',
          'booking_summary': 'Hariri ya oda',
          'entry_date': 'Kuingia',
          'exit_date': 'Kutoka',
          'total_hours': 'Saa za kukaa',
          'price': 'Gharama kwa saa',
          'total': 'Jumla',
          'pay_now': 'Lipa sasa',
          'choose_room': 'Chagua chumba',
          'payment_reference_number': 'KUMBUKUMBU NAMBA',
          'mpesa_guide':
              '1. Bofya kitufe kukopi namba,\n2. Piga *150*00# OK,\n2. Chagua # 3, Lipa kwa Mpesa,\n4. Chagua # 2 ingiza nambari ya biashara,\n5. Ingiza nambari hizi 3364545,\n6. Ingiza kumbukumbu namba ulizokopi,\n7. Ingiza PINI ya M-PESA na hakiki malipo,\n8. Rejea katika Aplikesheni na subiri kidogo.',
          'are_you_sure_you_want_to_cancel':
              'Unauhakika unataka kusitisha malipo?\nKusitisha malipo kutasitisha usasishaji wa moja kwa moja, sitisha tu endapo umeghairi kufanya malipo.',
          'waiting': 'Inasubiri...',
          'waiting_for_payment': 'Inasubiri malipo',
          'yes': 'Ndio',
          'no': 'Hapana',
          'no_reference_number': 'HAKUNA NAMBA YA MALIPO',
          'invalid_reference_number':
              'Namba yako ya malipo haikutengezwa kama ilivyotarajiwa kwa sababu ya kutokidhi baadhi ya vigezo. Tafadhali soma ujumbe ulioonyeshwa hapo juu rekebisha vigezo na jaribu tena. Kama tatizo litaendelea usichelee kuwasiliana nasi kupitia mawasiliano yaliyopo kwenye kitufe za zaidi.',
          'choose_operator': 'Changua mtandao',
          'continue': 'Endelea',
          'payment_made_successfully':
              'Malipo yako yamepokelewa kikamilifu upande wetu.',
          'continue_with_payment': 'Endelea na malipo',
          'your_purchase_was_successfully':
              'Malipo yako yamefanikiwa kikamilifu ',
          'your_payment_receipt_details': 'Taarifa za malipo yako',
          'nb': 'ANGALIZO',
          'do_not_share':
              'Risiti ya malipo ni taarifa ya siri, tafadhali usimpe ama kumwonyesha mtu..',
          'no_house_found': 'Hakuna taarifa katika ',
          'no_item_found': 'Hakuna taarifa katika',
          'no_house_found_description':
              'Hakuna huduma iliyopatika katika kitengo hiki, hii hutokea endapo kitengo kundi ulilochangua halikuoana na taarifa zilizopo kwenye kanzi data zetu. Tafadhali tembelea kitengo hili baada ya muda kidogo kuona kama taarifa zimepakiwa.',
          'book_house': 'Weka nyumba',
          'other': 'Zingine',
          'you_have_no_receipt': 'Huna risiti kwa sasa',
          'no_receipt_description':
              'Hauna risiti iliyo hai kwa sasa, risiti ya mwisho ambayo haijatumika itaonyeshwa hapa.',
          'no_service_found_for': 'Hakuna taarifa katika kundi la',
          'no_service_found_description':
              'Hakuna huduma zilipatikana katika kundi hili. Hili hutokea endapo taarifa mpya hazijapakiwa au mmiliki wa huduma aliziondoa.',
          'category_two': ' ',
          'price_per_hour': 'Bei kwa saa',
          'price_per_day': 'Bei kwa siku',
          'total_days': 'Jumla ya siku',
          'days': 'Siku',
          'hours': 'Saa',
          'minimum_days': 'Kiwango cha chini ni siku ',
          'minimum_hours': 'Kiwango cha chini ni saa ',
          'days_jm': ' ',
          'hours_jm': ' ',
          'choose_duration': 'Tafadhali changua muda',
          'amount': 'Kiasi',
          'try_fix': 'Tatua hilo swala',
          'seach_by_name_region_district': 'Tafuta kwa jina, mkoa au wilaya',
          'search_regions': 'Tafuta mikoa',
          'ok': 'SAWA',
          'no_results_found_for': 'Hakuna matokeo ya utafutaji wa ',
          'no_service_found_description_search':
              'Hakuna matokeo yaliyopatikana katika utafutaji wako, tafadhali angalia vyema utafutaji wako kisha jaribu tena.',
          'booking_type': 'Chagua aina ya uwekaji',
          'personal_booking': 'Oda yako binfsi',
          'cooperate_booking': 'Oda ya shirika',
          'book': 'Weka oda',
          'cooperate_number': 'Namba ya ushirika',
          'number_of_rooms': 'Idadi ya vyumba',
          'booked_rooms': 'Vyumba',
          'enter_cooperate_number': 'Ingiza namba ya ushirika',
          'cooperate_number_short': 'Ushirika',
          'check_guide':
              'Umefanikiwa kuweka kama shirika, tafadhali chukua kumbukumbu ya malipo kwa ili kuambatanisha wakati wa malipo. Tafadhali zingatia masharti na vigezo vya uwekaji wa ushirika.',
          'reference_number': 'Kumbukumbu',
          'confirm_operation': 'Angalizo',
          'no_description':
              'Hakuna maelezo yaliyowekwa na meneja kuhusiana na hii huduma, kama kuna jambo haliko sawa usisite kupiga simu na kuuliza',
          'Rentals': 'Kupangisha',
          'create_account': 'Unda Akaunti',
          'have_an_account': 'Je, una akaunti?',
          'phone_number': 'Nambari ya simu',
          'create_premium_account': 'Create Account',
          'sign_as_prememium': 'Sign in',
          'premium_account': 'Ingia',
          'not_member_yet': 'Je, huna akaunti?',
          'password': 'Nywila',
          'password_': 'Ingiza nywila kwa usahihi!',
          'phone_': 'Ingiza namba ya simu kwa usahihi!',
          'are_you_sure': 'Una uhakika unataka kuondoka?',
          'selcom_portal': 'SEHEMU YA MALIPO SELCOM',
        },
      };
}
