// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy1wVYAzuB9V9mRr9Qqpz-Cj8wivJFOIU',
    appId: '1:443536851257:web:e2617ab8c439cb5b4b68e8',
    messagingSenderId: '443536851257',
    projectId: 'tempo-application-tanzania',
    authDomain: 'tempo-application-tanzania.firebaseapp.com',
    storageBucket: 'tempo-application-tanzania.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxzvHY7aKFuL3cSKjq14MjFW6nCXDFC-o',
    appId: '1:443536851257:android:1f5df869bc24079b4b68e8',
    messagingSenderId: '443536851257',
    projectId: 'tempo-application-tanzania',
    storageBucket: 'tempo-application-tanzania.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAkG_jZCPjmWWiaClRUR1Fp9AcK0DfawM',
    appId: '1:443536851257:ios:0c2fbaa4ead15bb24b68e8',
    messagingSenderId: '443536851257',
    projectId: 'tempo-application-tanzania',
    storageBucket: 'tempo-application-tanzania.appspot.com',
    iosClientId: '443536851257-rj3tih3htodomkmt4v8126plu6ieguo0.apps.googleusercontent.com',
    iosBundleId: 'co.tz.tempo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAkG_jZCPjmWWiaClRUR1Fp9AcK0DfawM',
    appId: '1:443536851257:ios:0c2fbaa4ead15bb24b68e8',
    messagingSenderId: '443536851257',
    projectId: 'tempo-application-tanzania',
    storageBucket: 'tempo-application-tanzania.appspot.com',
    iosClientId: '443536851257-rj3tih3htodomkmt4v8126plu6ieguo0.apps.googleusercontent.com',
    iosBundleId: 'co.tz.tempo',
  );
}
